# Generated by Django 5.2.4 on 2025-07-28 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('km_salida', models.PositiveIntegerField()),
                ('fecha_regreso', models.DateTimeField(blank=True, null=True)),
                ('km_regreso', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=10)),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
